on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 9 1 * *"

name: Dashboard update

jobs:
  Dashboard-update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSCONNECT_USER: ${{ secrets.RSCONNECT_USER }}
      RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
      RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.2.0' # The R version to download
          
      - name: Install curl
        run: sudo apt -y install libcurl4-openssl-dev
        
      - name: Install textshaping dependencies
        run: sudo apt -y install libharfbuzz-dev libfribidi-dev

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            
      - name: Restore packages
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      - name: Install workflow dependencies
        run: |
          install.packages(c("rcmdcheck", "sessioninfo", "devtools", "rsconnect"))
        shell: Rscript {0}
   
      - name: Update data
        run: |
          source("get_data.R")
        shell: Rscript {0}

      - name: Authorize and deploy app
        run: |
          rsconnect::setAccountInfo(name='${{ secrets.RSCONNECT_USER }}', token='${{ secrets.RSCONNECT_TOKEN }}', secret='${{ secrets.RSCONNECT_SECRET }}')
          rsconnect::deployApp(account = 'analisemacro', forceUpdate = TRUE)
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Update data and deploy shiny app" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
